/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_signer_OpensslSigner */

#ifndef _Included_br_ufsc_labsec_libcryptosec_signer_OpensslSigner
#define _Included_br_ufsc_labsec_libcryptosec_signer_OpensslSigner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufsc_labsec_libcryptosec_signer_OpensslSigner
 * Method:    _sign
 * Signature: (I[BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_br_ufsc_labsec_libcryptosec_signer_OpensslSigner__1sign
  (JNIEnv *, jclass, jint, jbyteArray, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_signer_OpensslSigner
 * Method:    _verify
 * Signature: (I[B[BLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_br_ufsc_labsec_libcryptosec_signer_OpensslSigner__1verify
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
