/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_keys_OpensslPrivateKey */

#ifndef _Included_br_ufsc_labsec_libcryptosec_keys_OpensslPrivateKey
#define _Included_br_ufsc_labsec_libcryptosec_keys_OpensslPrivateKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufsc_labsec_libcryptosec_keys_OpensslPrivateKey
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_keys_OpensslPrivateKey__1delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
