/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class x509_OpenSSLRDNSequence */

#ifndef _Included_x509_OpenSSLRDNSequence
#define _Included_x509_OpenSSLRDNSequence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     x509_OpenSSLRDNSequence
 * Method:    _init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_x509_OpenSSLRDNSequence__1init
  (JNIEnv *, jobject);

/*
 * Class:     x509_OpenSSLRDNSequence
 * Method:    _addEntry
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT void JNICALL Java_x509_OpenSSLRDNSequence__1addEntry__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     x509_OpenSSLRDNSequence
 * Method:    _addEntry
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT void JNICALL Java_x509_OpenSSLRDNSequence__1addEntry__Ljava_lang_String_2_3Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}

#endif
#endif
