/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crl_OpenSSLCertificateRevocationList */

#ifndef _Included_crl_OpenSSLCertificateRevocationList
#define _Included_crl_OpenSSLCertificateRevocationList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crl_OpenSSLCertificateRevocationList
 * Method:    _getPemEncoded
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_crl_OpenSSLCertificateRevocationList__1getPemEncoded
  (JNIEnv *, jobject);

/*
 * Class:     crl_OpenSSLCertificateRevocationList
 * Method:    _getDerEncoded
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_crl_OpenSSLCertificateRevocationList__1getDerEncoded
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
