/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crl_CertificateRevocationListBuilder */

#ifndef _Included_crl_CertificateRevocationListBuilder
#define _Included_crl_CertificateRevocationListBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_crl_CertificateRevocationListBuilder__1init__
  (JNIEnv *, jobject);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crl_CertificateRevocationListBuilder__1init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _init
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_crl_CertificateRevocationListBuilder__1init___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _setSerialNumber
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_crl_CertificateRevocationListBuilder__1setSerialNumber__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _setSerialNumber
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_crl_CertificateRevocationListBuilder__1setSerialNumber__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _setVersion
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_crl_CertificateRevocationListBuilder__1setVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _setIssuer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_crl_CertificateRevocationListBuilder__1setIssuer
  (JNIEnv *, jobject, jint);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _setLastUpdate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_crl_CertificateRevocationListBuilder__1setLastUpdate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _setNextUpdate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_crl_CertificateRevocationListBuilder__1setNextUpdate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _addRevokedCertificate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_crl_CertificateRevocationListBuilder__1addRevokedCertificate
  (JNIEnv *, jobject, jint);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _addRevokedCertificates
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_crl_CertificateRevocationListBuilder__1addRevokedCertificates
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     crl_CertificateRevocationListBuilder
 * Method:    _sign
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_crl_CertificateRevocationListBuilder__1sign
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
