/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class crl_OpenSSLRevokedCertificate */

#ifndef _Included_crl_OpenSSLRevokedCertificate
#define _Included_crl_OpenSSLRevokedCertificate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     crl_OpenSSLRevokedCertificate
 * Method:    _init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_crl_OpenSSLRevokedCertificate__1init
  (JNIEnv *, jobject);

/*
 * Class:     crl_OpenSSLRevokedCertificate
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_crl_OpenSSLRevokedCertificate__1delete
  (JNIEnv *, jobject);

/*
 * Class:     crl_OpenSSLRevokedCertificate
 * Method:    _setSerialNumber
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_crl_OpenSSLRevokedCertificate__1setSerialNumber__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     crl_OpenSSLRevokedCertificate
 * Method:    _setSerialNumber
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_crl_OpenSSLRevokedCertificate__1setSerialNumber__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     crl_OpenSSLRevokedCertificate
 * Method:    _setRevocationDate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_crl_OpenSSLRevokedCertificate__1setRevocationDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     crl_OpenSSLRevokedCertificate
 * Method:    _setReasonCode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_crl_OpenSSLRevokedCertificate__1setReasonCode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
