/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JniObject */

#ifndef _Included_jni_JniObject
#define _Included_jni_JniObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JniObject
 * Method:    _delete
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jni_JniObject__1delete
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}

#endif
#endif
