/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder */

#ifndef _Included_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
#define _Included_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1init__
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _init
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1init___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1init__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1delete
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _setSerialNumber
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1setSerialNumber__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _setSerialNumber
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1setSerialNumber__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _setVersion
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1setVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _setSubject
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1setSubject
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _setIssuer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1setIssuer
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _setNotBefore
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1setNotBefore
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _setNotAfter
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1setNotAfter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _setPublicKey
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1setPublicKey__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _setPublicKey
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1setPublicKey___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _setPublicKey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1setPublicKey__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder
 * Method:    _sign
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder__1sign
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
