/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class certificate_OpenSSLCertificate */

#ifndef _Included_certificate_OpenSSLCertificate
#define _Included_certificate_OpenSSLCertificate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     certificate_OpenSSLCertificate
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_certificate_OpenSSLCertificate__1delete
  (JNIEnv *, jobject);

/*
 * Class:     certificate_OpenSSLCertificate
 * Method:    _getPemEncoded
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_certificate_OpenSSLCertificate__1getPemEncoded
  (JNIEnv *, jobject);

/*
 * Class:     certificate_OpenSSLCertificate
 * Method:    _getDerEncoded
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_certificate_OpenSSLCertificate__1getDerEncoded
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
