/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence */

#ifndef _Included_br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence
#define _Included_br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence
 * Method:    _init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence__1init
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence__1delete
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence
 * Method:    _addEntry
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence__1addEntry__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence
 * Method:    _addEntry
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence__1addEntry__Ljava_lang_String_2_3Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
