/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class keys_OpenSSLKeyFactory */

#ifndef _Included_keys_OpenSSLKeyFactory
#define _Included_keys_OpenSSLKeyFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     keys_OpenSSLKeyFactory
 * Method:    _loadEngine
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Lengine/EngineCommand;)I
 */
JNIEXPORT jint JNICALL Java_keys_OpenSSLKeyFactory__1loadEngine
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
