/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class keys_OpenSSLPrivateKey */

#ifndef _Included_keys_OpenSSLPrivateKey
#define _Included_keys_OpenSSLPrivateKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     keys_OpenSSLPrivateKey
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_keys_OpenSSLPrivateKey__1delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
