/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class keys_OpenSSLKeyPair */

#ifndef _Included_keys_OpenSSLKeyPair
#define _Included_keys_OpenSSLKeyPair
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     keys_OpenSSLKeyPair
 * Method:    _loadKeyPair
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_keys_OpenSSLKeyPair__1loadKeyPair
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     keys_OpenSSLKeyPair
 * Method:    _getPublicKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_keys_OpenSSLKeyPair__1getPublicKey
  (JNIEnv *, jobject);

/*
 * Class:     keys_OpenSSLKeyPair
 * Method:    _getPrivateKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_keys_OpenSSLKeyPair__1getPrivateKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
