/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class keys_OpenSSLPublicKey */

#ifndef _Included_keys_OpenSSLPublicKey
#define _Included_keys_OpenSSLPublicKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     keys_OpenSSLPublicKey
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_keys_OpenSSLPublicKey__1delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
