package x509;

public enum RDNSequenceEntryType {
	COUNTRY("COUNTRY"),
	STATE_OR_PROVINCE("STATE_OR_PROVINCE"),
	LOCALITY("LOCALITY"),
	ORGANIZATION("ORGANIZATION"),
	ORGANIZATION_UNIT("ORGANIZATION_UNIT"),
	COMMON_NAME("COMMON_NAME"),
	EMAIL("EMAIL"),
	DN_QUALIFIER("DN_QUALIFIER"),
	SERIAL_NUMBER("SERIAL_NUMBER"),
	TITLE("TITLE"),
	SURNAME("SURNAME"),
	GIVEN_NAME("GIVEN_NAME"),
	INITIALS("INITIALS"),
	PSEUDONYM("PSEUDONYM"),
	GENERATION_QUALIFIER("GENERATION_QUALIFIER"),
	DOMAIN_COMPONENT("DOMAIN_COMPONENT"),
	UNKNOWN("UNKNOWN");
	
	private String name;
	
	RDNSequenceEntryType(String name)
	{
		this.name = name;
	}
	
	public String getName()
	{
		return this.name;
	}
}
