/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate */

#ifndef _Included_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate
#define _Included_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate__1delete
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate
 * Method:    _getPemEncoded
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate__1getPemEncoded
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate
 * Method:    _getDerEncoded
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate__1getDerEncoded
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
