/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_engine_OpensslDynamicEngine */

#ifndef _Included_br_ufsc_labsec_libcryptosec_engine_OpensslDynamicEngine
#define _Included_br_ufsc_labsec_libcryptosec_engine_OpensslDynamicEngine
#ifdef __cplusplus
extern "C" {
#endif

bool engine_suport_loaded = false;

/*
 * Class:     br_ufsc_labsec_libcryptosec_engine_OpensslDynamicEngine
 * Method:    _init
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Lbr/ufsc/labsec/libcryptosec/engine/OpensslEngineCommand;)I
 */
JNIEXPORT jint JNICALL Java_br_ufsc_labsec_libcryptosec_engine_OpensslDynamicEngine__1init
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     br_ufsc_labsec_libcryptosec_engine_OpensslDynamicEngine
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_engine_OpensslDynamicEngine__1delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
