/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class engine_DynamicEngine */

#ifndef _Included_engine_DynamicEngine
#define _Included_engine_DynamicEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     engine_DynamicEngine
 * Method:    _init
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Lengine/EngineCommand;)I
 */
JNIEXPORT jint JNICALL Java_engine_DynamicEngine__1init
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     engine_DynamicEngine
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_engine_DynamicEngine__1delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
