######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 11 12:53:56 2012
######################################################################

TEMPLATE = lib
TARGET = 
LIBS += -lcryptosec -lc
DEPENDPATH += . \
              include/certificate \
              include/crl \
              include/engine \
              include/exceptions \
              include/keys \
              include/signer \
              include/util \
              include/x509 \
              include/certificate/src \
              include/crl/src \
              include/engine/src \
              include/keys/src \
              include/signer/src \
              include/x509/src
INCLUDEPATH += . include /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79/include /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79/include/linux /usr/java/jdk1.7.0_79/include/

# Input
HEADERS += include/certificate/br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate.h \
           include/certificate/br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder.h \
           include/certificate/br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest.h \
           include/crl/br_ufsc_labsec_libcryptosec_crl_OpensslCertificateRevocationList.h \
           include/crl/br_ufsc_labsec_libcryptosec_crl_OpensslCertificateRevocationListBuilder.h \
           include/crl/br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate.h \
           include/engine/br_ufsc_labsec_libcryptosec_engine_OpensslDynamicEngine.h \
           include/exceptions/EnumConversionException.h \
           include/keys/br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair.h \
           include/keys/br_ufsc_labsec_libcryptosec_keys_OpensslPrivateKey.h \
           include/keys/br_ufsc_labsec_libcryptosec_keys_OpensslPublicKey.h \
           include/signer/br_ufsc_labsec_libcryptosec_signer_OpensslSigner.h \
           include/util/Util.h \
           include/x509/br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence.h
SOURCES += include/certificate/br_ufsc_labsec_libcryptosec_certificate_OpensslCertificate.cpp \
           include/certificate/br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateBuilder.cpp \
           include/certificate/br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest.cpp \
           include/crl/br_ufsc_labsec_libcryptosec_crl_OpensslCertificateRevocationList.cpp \
           include/crl/br_ufsc_labsec_libcryptosec_crl_OpensslCertificateRevocationListBuilder.cpp \
           include/crl/br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate.cpp \
           include/engine/br_ufsc_labsec_libcryptosec_engine_OpensslDynamicEngine.cpp \
           include/keys/br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair.cpp \
           include/keys/br_ufsc_labsec_libcryptosec_keys_OpensslPrivateKey.cpp \
           include/keys/br_ufsc_labsec_libcryptosec_keys_OpensslPublicKey.cpp \
           include/signer/br_ufsc_labsec_libcryptosec_signer_OpensslSigner.cpp \
           include/x509/br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequence.cpp
