/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_signer_OpensslSigner */

#ifndef _Included_br_ufsc_labsec_libcryptosec_signer_OpensslSigner
#define _Included_br_ufsc_labsec_libcryptosec_signer_OpensslSigner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufsc_labsec_libcryptosec_signer_OpensslSigner
 * Method:    _sign
 * Signature: (Lbr/ufsc/labsec/libcryptosec/keys/OpensslPrivateKey;[BLbr/ufsc/labsec/libcryptosec/digester/OpensslMessageDigestAlgorithm;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_br_ufsc_labsec_libcryptosec_signer_OpensslSigner__1sign
  (JNIEnv *, jclass, jobject, jbyteArray, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_signer_OpensslSigner
 * Method:    _verify
 * Signature: (Lbr/ufsc/labsec/libcryptosec/keys/OpensslPublicKey;[B[BLbr/ufsc/labsec/libcryptosec/digester/OpensslMessageDigestAlgorithm;)Z
 */
JNIEXPORT jboolean JNICALL Java_br_ufsc_labsec_libcryptosec_signer_OpensslSigner__1verify
  (JNIEnv *, jclass, jobject, jbyteArray, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
