/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest */

#ifndef _Included_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest
#define _Included_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest__1delete
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest
 * Method:    _init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest__1init__
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest
 * Method:    _init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest__1init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest
 * Method:    _init
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_br_ufsc_labsec_libcryptosec_certificate_OpensslCertificateRequest__1init___3B
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
