/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_keys_OpensslKeyFactory */

#ifndef _Included_br_ufsc_labsec_libcryptosec_keys_OpensslKeyFactory
#define _Included_br_ufsc_labsec_libcryptosec_keys_OpensslKeyFactory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
