/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair */

#ifndef _Included_br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair
#define _Included_br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair
 * Method:    _init
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair__1init
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair__1delete
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair
 * Method:    _getPublicKey
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair__1getPublicKey
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair
 * Method:    _getPrivateKey
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_br_ufsc_labsec_libcryptosec_keys_OpensslKeyPair__1getPrivateKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
