/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate */

#ifndef _Included_br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate
#define _Included_br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate
 * Method:    _init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate__1init
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate
 * Method:    _delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate__1delete
  (JNIEnv *, jobject);

/*
 * Class:     br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate
 * Method:    _setSerialNumber
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate__1setSerialNumber__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate
 * Method:    _setSerialNumber
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate__1setSerialNumber__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate
 * Method:    _setRevocationDate
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate__1setRevocationDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate
 * Method:    _setReasonCode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificate__1setReasonCode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
