/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificateReasonCode */

#ifndef _Included_br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificateReasonCode
#define _Included_br_ufsc_labsec_libcryptosec_crl_OpensslRevokedCertificateReasonCode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
