/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequenceEntryType */

#ifndef _Included_br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequenceEntryType
#define _Included_br_ufsc_labsec_libcryptosec_x509_OpensslRdnSequenceEntryType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
