/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_jni_JniObject */

#ifndef _Included_br_ufsc_labsec_libcryptosec_jni_JniObject
#define _Included_br_ufsc_labsec_libcryptosec_jni_JniObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufsc_labsec_libcryptosec_jni_JniObject
 * Method:    _delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_br_ufsc_labsec_libcryptosec_jni_JniObject__1delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
