/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufsc_labsec_libcryptosec_test_OpenSSLCertificateRevocationListTest */

#ifndef _Included_br_ufsc_labsec_libcryptosec_test_OpenSSLCertificateRevocationListTest
#define _Included_br_ufsc_labsec_libcryptosec_test_OpenSSLCertificateRevocationListTest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
